name: json_localizations
description: A minimal JSON localization package built on LocalizationsDelegate.
version: 0.6.0
homepage: https://github.com/erf/json_localizations

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1
